### Test Sign Up
POST http://localhost:3000/api/signup
Content-Type: application/json

{
  "email": "example@example.com",
  "password": "Ts_12345678"
}

#input 1.email 2.password
#returen null
#function send input to database 


### Test Login
POST http://localhost:3000/api/login
Content-Type: application/json

{
  "email": "example@example.com",
  "password": "testpassword"
}

#input 1.email 2.password
#returen token
#function send token to memcached


### Create problem
POST http://localhost:3000/api/dumdb/vueapp/problems
Content-Type: application/json

{
  "action": "create",
  "data": {
    "username": "javad",
    "chat_id": "5656777",
    "problem_msg": "dsgfdfhggf",
    "status": "open"
  }
}

### Get problems
POST http://localhost:3000/api/dumdb/vueapp/problems
Content-Type: application/json

{
  "action": "get",
  "filter": {
    "username": "javad"
  }
}


### Create profile
POST http://localhost:3000/api/dumdb/vueapp/profile
Content-Type: application/json

{
  "action": "create",
  "data": {
    "email": "kasiri.javad@gmail.com",
    "username": "123456789",
    "name": "javad kasiri",
    "phone": "+989123456789",
    "role": "admin"
  }
}

### Get profile
POST http://localhost:3000/api/dumdb/vueapp/profile
Content-Type: application/json

{
  "action": "get",
  "filter": {
    "username": "123456789"
  }
}

### Create custumer chat message
POST http://localhost:3000/api/dumdb/vueapp/chats
Content-Type: application/json

{
  "action": "create",
  "data": {
    "conversationId": "conv_026",
    "senderId": "customer_009",
    "receiverId": "user_009",
    "sender": "Emma Stone",
    "text": "Perfect. I’ll visit tomorrow morning.",
    "time": "3:43 PM",
      "side": "left"
  }
}

### Create user chat message
POST http://localhost:3000/api/dumdb/vueapp/chats
Content-Type: application/json

{
  "action": "create",
  "data": {
    "conversationId": "conv_026",
    "senderId": "user_009",
    "receiverId": "customer_009",
    "sender": "Michael",
    "text": "We’ll be ready to assist. Thanks for checking in!",
    "time": "3:44 PM",
    "side": "right"
  }
}

### Get chat messages
POST http://localhost:3000/api/dumdb/vueapp/chats
Content-Type: application/json

{
  "action": "get",
  "filter": {}
}
